apiVersion: v1
kind: Service
metadata:
    name: "yelpcampk8s-ee7c"
    labels:
        app: "yelpcampk8s-ee7c"
spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "yelpcampk8s-ee7c"